version: 2

sources:
  - name: MVC_C
    database: zoomcamp-db
    schema: public
    tables:
      - name: MVC_C_2012
      description: >
        The Motor Vehicle Collisions crash tables contains details on the crash event.
        Each row represents a crash event. The Motor Vehicle Collisions data tables 
        contain information from all police reported motor vehicle collisions in NYC. 
        The police report (MV104-AN) is required to be filled out for collisions where 
        someone is injured or killed, or where there is at least $1000 worth of damage 
        (https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/ny_overlay_mv-104an_rev05_2004.pdf). 
        It should be noted that the data is preliminary and subject to change when the MV-104AN 
        forms are amended based on revised crash details.For the most accurate, up to date 
        statistics on traffic fatalities, please refer to the NYPD Motor Vehicle Collisions page 
        (updated weekly) or Vision Zero View (updated monthly).

      columns:
          - name: collision_id
            description: Unique record code generated by system. Primary Key for Crash table.

          - name: crash_date
            description: Occurrence date of collision
          
          - name: crash_time
            description: Occurrence time of collision

          - name: borough
            description: Borough where collision occurred

          - name: injured
            description: Number of persons injured
          
          - name: killed
            description: Number of persons killed

          - name: vhc_1_code
            description: Type of vehicle based on the selected vehicle category 
            (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)

          - name: contr_f_vhc_1
            description: Factors contributing to the collision for designated vehicle
          
          - name: vhc_2_code
            description: Type of vehicle based on the selected vehicle category 
            (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)

          - name: contr_f_vhc_2
            description: Factors contributing to the collision for designated vehicle

          - name: vhc_3_code
            description: Type of vehicle based on the selected vehicle category 
            (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)

          - name: contr_f_vhc_3
            description: Factors contributing to the collision for designated vehicle

          - name: vhc_4_code
            description: Type of vehicle based on the selected vehicle category 
            (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)

          - name: contr_f_vhc_4
            description: Factors contributing to the collision for designated vehicle

      - name: MVC_C_2013
      - name: MVC_C_2014
      - name: MVC_C_2015
      - name: MVC_C_2016
      - name: MVC_C_2017
      - name: MVC_C_2018
      - name: MVC_C_2019
      - name: MVC_C_2020
      - name: MVC_C_2021
      - name: MVC_C_2022
      - name: MVC_C_2023

  - name: MVC_V
    database: zoomcamp-db
    schema: public
    tables:
      - name: MVC_V_2012
      description: >
        The Motor Vehicle Collisions vehicle table contains details on each vehicle 
        involved in the crash. Each row represents a motor vehicle involved in a crash. 
        The data in this table goes back to April 2016 when crash reporting switched 
        to an electronic system.The Motor Vehicle Collisions data tables contain 
        information from all police reported motor vehicle collisions in NYC. The police 
        report (MV104-AN) is required to be filled out for collisions where someone is 
        injured or killed, or where there is at least $1000 worth of damage 
        (https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/ny_overlay_mv-104an_rev05_2004.pdf). 
        It should be noted that the data is preliminary and subject to change when the MV-104AN 
        forms are amended based on revised crash details.

      columns:
          - name: unique_id
            description: Unique record code generated by system. Primary Key.

          - name: collision_id
            description: Crash identification code. Foreign Key, matches unique_id from 
            the Crash table.
  
          - name: crash_date
            description: Occurrence date of collision

          - name: crash_time
            description: Occurrence time of collision

          - name: vhc_type
            description: Type of vehicle based on the selected vehicle category 
            (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)

          - name: vhc_dmg
            description: Location on the vehicle where most of the damage occurred

          - name: dr_sex
            description: Gender of driver

          - name: dr_lic_status
            description: License, permit, unlicensed

          - name: vhc_year
            description: Year the vehicle was manufactured

          - name: vhc_occupants
            description: Number of vehicle occupants

          - name: state_reg
            description: State where vehicle is registered.

          - name: contr_f
            description: Factors contributing to the collision for designated vehicle

      - name: MVC_V_2013
      - name: MVC_V_2014
      - name: MVC_V_2015
      - name: MVC_V_2016
      - name: MVC_V_2017
      - name: MVC_V_2018
      - name: MVC_V_2019
      - name: MVC_V_2020
      - name: MVC_V_2021
      - name: MVC_V_2022
      - name: MVC_V_2023
      
  - name: MVC_P
    database: zoomcamp-db
    schema: public
    tables:
      - name: MVC_P_2012
      description: >
        The Motor Vehicle Collisions person table contains details for people 
        involved in the crash. Each row represents a person (driver, occupant, 
        pedestrian, bicyclist,..) involved in a crash. The data in this table 
        goes back to April 2016 when crash reporting switched to an electronic 
        system. The Motor Vehicle Collisions data tables contain information 
        from all police reported motor vehicle collisions in NYC. The police 
        report (MV104-AN) is required to be filled out for collisions where 
        someone is injured or killed, or where there is at least $1000 worth 
        of damage 
        (https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/ny_overlay_mv-104an_rev05_2004.pdf). 
        It should be noted that the data is preliminary and subject to change 
        when the MV-104AN forms are amended based on revised crash details.

      columns:
          - name: unique_id
            description: Unique record code generated by system. Primary Key.

          - name: collision_id
            description: Crash identification code. Foreign Key, matches unique_id from 
            the Crash table.
  
          - name: crash_date
            description: Occurrence date of collision

          - name: crash_time
            description: Occurrence time of collision

          - name: ejection
            description: Indicates the following - Not ejected, partially ejected, 
            or ejected from the vehicle

          - name: body_inj
            description: Injured body area (i.e. head, face, neck, etc.)

          - name: person_inj 
            description: Injured, killed, unspecified

          - name: pos_in_vhc
            description: Seating position #1-#8 (i.e. driver, front passenger, etc.)

          - name: safety_equip
            description: Safety equipment being used (i.e. lap belt, harness, child restraint, air bag, etc.)

          - name: person_type
            description: Bicyclist, Motor Vehicle Occupant, Pedestrian,

          - name: age
            description: Automatically calculated based on date of birth

          - name: sex
            description: Gender of person

          - name: emot_status
            description: Apparent death, unconscious, semiconscious, etc.

          - name: contr_f
            description: Factors contributing to the collision for designated vehicle

      - name: MVC_P_2013
      - name: MVC_P_2014
      - name: MVC_P_2015
      - name: MVC_P_2016
      - name: MVC_P_2017
      - name: MVC_P_2018
      - name: MVC_P_2019
      - name: MVC_P_2020
      - name: MVC_P_2021
      - name: MVC_P_2022
      - name: MVC_P_2023
      

models:
    - name: mvc_sum_2012
      description: >
        The Motor Vehicle Collisions summarize tables contains details for generalized
        data from 3 source tables: Crashes, Vehicles and Person. 

      columns:
          - name: year
            description: Occurrence year of collisions

          - name: injured 
            description: Number of persons injured
  
          - name: inj_am
            description: Total amount corresponding to the selected value

          - name: killed
            description: Number of persons killed

          - name: killed_am
            description: Total amount corresponding to the selected value
          
          - name: borough
            description: Borough where collision occurred
  
          - name: borough_am
            description: Total amount corresponding to the selected value

          - name: vhc_type
            description: Type of vehicle based on the selected vehicle category 
            (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)

          - name: vhc_type_am
            description: Total amount corresponding to the selected value
          
          - name: contr_f
            description: Factors contributing to the collision for designated vehicle
  
          - name: contr_f_am
            description: Total amount corresponding to the selected value

          - name: vhc_dmg
            description: Location on the vehicle where most of the damage occurred

          - name: vhc_dmg_am
            description: Total amount corresponding to the selected value
          
          - name: vhc_year
            description: Year the vehicle was manufactured
  
          - name: vhc_year_am
            description: Total amount corresponding to the selected value

          - name: vhc_occupants
            description: Number of vehicle occupants

          - name: vhc_oc_am
            description: Total amount corresponding to the selected value
          
          - name: dr_lic_status
            description: License, permit, unlicensed
  
          - name: dr_lic_am
            description: Total amount corresponding to the selected value

          - name: state_reg
            description: State where vehicle is registered.

          - name: st_reg_am
            description: Total amount corresponding to the selected value
          
          - name: ejection
            description: Indicates the following - Not ejected, partially ejected, 
            or ejected from the vehicle
  
          - name: ej_am
            description: Total amount corresponding to the selected value

          - name: body_inj 
            description: Injured body area (i.e. head, face, neck, etc.)

          - name: body_inj_am
            description: Total amount corresponding to the selected value
          
          - name: age
            description: Automatically calculated based on date of birth
  
          - name: sex
            description: Gender of person

          - name: age_am
            description: Total amount corresponding to the selected value

          - name: ind
            description: Index

    - name: mvc_sum_2013
    - name: mvc_sum_2014
    - name: mvc_sum_2015
    - name: mvc_sum_2016
    - name: mvc_sum_2017
    - name: mvc_sum_2018
    - name: mvc_sum_2019
    - name: mvc_sum_2020
    - name: mvc_sum_2021
    - name: mvc_sum_2022
    - name: mvc_sum_2023
    
    - name: mvc_sum_all
    description: >
        The Motor Vehicle Collisions summarize table contains details for generalized
        data from 3 source tables: Crashes, Vehicles and Person for all presented years. 

    - name: mvc_dataset_overview
      description: >
        The Motor Vehicle Collisions dataset overview table contains details about 
        missing or not specified data in the dataset in absolute and relative terms, 
        distributed by year.

      columns:
          - name: year
            description: Occurrence year of collisions

          - name: total_crashes_am
            description: Sum of crashes records from MVC_C tables distributed by year

          - name: total_vhc_am
            description: Sum of vehicles records from MVC_V tables distributed by year
  
          - name: total_person_am
            description: Sum of person records from MVC_P tables distributed by year

          - name: no_vhc_data_am
            description: Sum of collisions without any data about vehicles distributed by year

          - name: no_vhc_data_%
            description: Percentage of collisions without any data about vehicles distributed by year
  
          - name: no_person_data_am
            description: Sum of collisions without any data about persons distributed by year

          - name: no_person_data_%
            description: Percentage of collisions without any data about persons distributed by year

          - name: no_borough_data
            description: Sum of collisions without any data about boroughs distributed by year
  
          - name: no_borough_data_%
            description: Percentage of collisions without any data about boroughs distributed by year

          - name: no_contr_f_data
            description: Sum of collisions without any data about contributing factors distributed by year

          - name: no_contr_f_data_%
            description: Percentage of collisions without any data about contributing factors distributed by year
  
          - name: no_vhc_type_data
            description: Sum of collisions without any data about vehicle type distributed by year

          - name: no_vhc_type_data_%
            description: Percentage of collisions without any data about vehicle type distributed by year

          - name: no_vhc_year_data
            description: Sum of collisions without any data about year the vehicle was manufactured distributed by year
  
          - name: no_vhc_year_data_%
            description: Percentage of collisions without any data about year the vehicle was manufactured distributed by year

          - name: no_dr_lic_status_data
            description: Sum of collisions without any data about driver licence status distributed by year

          - name: no_dr_lic_status_data_% 
            description: Percentage of collisions without any data about driver licence status distributed by year

          - name: no_age_data
            description: Sum of collisions without any data about driver age distributed by year

          - name: no_age_data_%
            description: Percentage of collisions without any data about driver age distributed by year

          - name: no_sex_data
            description: Sum of collisions without any data about driver sex distributed by year

          - name: no_sex_data_%
            description: Percentage of collisions without any data about driver sex distributed by year


    - name: mvc_crashes_per_hour
      description: >
        The Motor Vehicle Collisions crashes per hour table contains generalize data about 
        crashes and injures, distributed by time interval(1 hour).

      columns:
          - name: year
            description: Occurrence year of collisions

          - name: month
            description: Occurrence month of collisions

          - name: time_interval
            description: Occurrence time interval of collisions
  
          - name: all_amount
            description: Sum of all collisions in selected year, month and time interval

          - name: injured_am
            description: Sum of all collisions with injuries in selected year, month and time interval

          - name: killed_am
            description: Sum of all collisions with deaths in selected year, month and time interval
  
          - name: from time
            description: Start of time interval

          - name: to time
            description: End of time interval

    - name: mvc_crashes_per_month
      description: >
        The Motor Vehicle Collisions crashes per month table contains generalize data about 
        crashes and injures, distributed by years and months.

      columns:
          - name: year
            description: Occurrence year of collisions

          - name: month
            description: Occurrence month of collisions

          - name: all_amount
            description: Sum of all collisions in selected year and month 

          - name: injured_am
            description: Sum of all collisions with injuries in selected year and month

          - name: killed_am
            description: Sum of all collisions with deaths in selected year and month
  
