
"Motor Vehicle Collisions (2012-2023) New York City" 
MVC_NYC = {'description': None,
 'archived': False,
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Motor Vehicle Collisions (2012-2023) New York City',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT SUM(total_crashes_am) AS "Total Crashes", SUM(total_vhc_am) AS "Total Vehicles involved in Crashes", SUM(total_person_am)  AS "Total Persons involved in Crashes"\r\nFROM "MVC_summarize".mvc_dataset_overview',
   'template-tags': {}},
  'database': 2},
 'display': 'object',
 'collection_preview': True,
 'visualization_settings': {'column_settings': {'["name","sum"]': {'column_title': 'Total Crashes'},
   '["name","sum_2"]': {'column_title': 'Total Vehicles involved in Crashes'},
   '["name","sum_3"]': {'column_title': 'Total Persons involved in Crashes'}}}
}

"Motor Vehicle Collisions (2012-2023) New York City Dataset Overview"
MVC_NYC_DO = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'year',
   'field_ref': ['field', 'year', {'base-type': 'type/Integer'}],
   'name': 'year',
   'base_type': 'type/Integer',
   'effective_type': 'type/Integer',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 12, 'nil%': 0.0},
    'type': {'type/Number': {'min': 2012.0,
      'q1': 2014.5,
      'q3': 2020.5,
      'max': 2023.0,
      'sd': 3.605551275463989,
      'avg': 2017.5}}}},
  {'display_name': 'no vhc data %',
   'field_ref': ['field', 'no vhc data %', {'base-type': 'type/Decimal'}],
   'name': 'no vhc data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 4, 'nil%': 0.0},
    'type': {'type/Number': {'min': 0.0,
      'q1': 0.0,
      'q3': 4.0,
      'max': 100.0,
      'sd': 38.66483799228566,
      'avg': 17.333333333333332}}}},
  {'display_name': 'no person data %',
   'field_ref': ['field', 'no person data %', {'base-type': 'type/Decimal'}],
   'name': 'no person data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 5, 'nil%': 0.0},
    'type': {'type/Number': {'min': 0.0,
      'q1': 0.0,
      'q3': 80.0,
      'max': 82.0,
      'sd': 38.47657689682087,
      'avg': 29.416666666666668}}}},
  {'display_name': 'no vhc type data %',
   'field_ref': ['field', 'no vhc type data %', {'base-type': 'type/Decimal'}],
   'name': 'no vhc type data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 7, 'nil%': 0.0},
    'type': {'type/Number': {'min': 0.0,
      'q1': 1.675444679663241,
      'q3': 13.5,
      'max': 100.0,
      'sd': 37.11927947968426,
      'avg': 21.25}}}},
  {'display_name': 'no age data %',
   'field_ref': ['field', 'no age data %', {'base-type': 'type/Decimal'}],
   'name': 'no age data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 12, 'nil%': 0.0},
    'type': {'type/Number': {'min': 2.0,
      'q1': 13.5,
      'q3': 74.5,
      'max': 78.0,
      'sd': 30.823421830376542,
      'avg': 34.916666666666664}}}},
  {'display_name': 'no sex data %',
   'field_ref': ['field', 'no sex data %', {'base-type': 'type/Decimal'}],
   'name': 'no sex data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 6, 'nil%': 0.0},
    'type': {'type/Number': {'min': 14.0,
      'q1': 15.720759220056127,
      'q3': 78.49845994432174,
      'max': 100.0,
      'sd': 41.048751503547585,
      'avg': 44.5}}}},
  {'display_name': 'no borough data %',
   'field_ref': ['field', 'no borough data %', {'base-type': 'type/Decimal'}],
   'name': 'no borough data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 8, 'nil%': 0.0},
    'type': {'type/Number': {'min': 23.0,
      'q1': 24.5,
      'q3': 35.17712434446771,
      'max': 38.0,
      'sd': 5.690901829794961,
      'avg': 31.25}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Motor Vehicle Collisions (2012-2023) New York City Dataset Overview',
 'embedding_params': None,
 'cache_ttl': None,
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT "year", "no_vhc_data_%" AS "No Vhc Data %", "no_person_data_%" AS "No Person Data %",  "no_vhc_type_data_%" AS "No Vhc Type Data %", \r\n"no_age_data_%" AS "No Age Data %", "no_sex_data_%" AS "No Sex Data %", "no_borough_data_%" AS "No Borough Data %"\r\nFROM "MVC_summarize".mvc_dataset_overview',
   'template-tags': {}},
  'database': 2},
 'parameter_mappings': [],
 'display': 'bar',
 'collection_preview': True,
 'visualization_settings': {'graph.dimensions': ['year'],
  'graph.series_order_dimension': None,
  'graph.series_order': None,
  'graph.y_axis.auto_split': False,
  'graph.metrics': ['no vhc data %',
   'no vhc type data %',
   'no person data %',
   'no age data %',
   'no borough data %',
   'no sex data %']},
 'parameters': [],
 'dataset': False
}

"Vehicle Types involved in Crashes"
VT_iiC = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Vehicle Types involved in Crashes',
   'field_ref': ['field',
    'Vehicle Types involved in Crashes',
    {'base-type': 'type/Text'}],
   'name': 'Vehicle Types involved in Crashes',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 372, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0.005376344086021505,
      'average-length': 6.599462365591398}}}},
  {'display_name': 'amount',
   'field_ref': ['field', 'amount', {'base-type': 'type/Decimal'}],
   'name': 'amount',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 123, 'nil%': 0},
    'type': {'type/Number': {'min': 3,
      'q1': 6.4829120355062635,
      'q3': 40.877249736984304,
      'max': 1030335,
      'sd': 80954.95294135342,
      'avg': 9472.002688172042}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Vehicle Types involved in Crashes',
 'dataset_query': {'type': 'native',
  'native': {'query': 'with tbl AS(\r\nSELECT vhc_type_ AS vhc_type, SUM(vhc_type_am) AS vhc_type_am FROM (\r\n\tSELECT CASE\r\n\tWHEN lower(vhc_type) LIKE \'passenger%\' THEN \'Passenger Vehicle\'\r\n\twhen lower(vhc_type) LIKE \'%sport utility%\' THEN \'Sport Utility / Station Wagon\'\r\n\twhen lower(vhc_type) LIKE \'taxi%\' THEN \'Taxi\'\r\n\twhen lower(vhc_type) LIKE \'pick%\' THEN \'Pick-up Truck\'\r\n\twhen lower(vhc_type) LIKE \'bus%\' THEN \'Bus\'\r\n\twhen lower(vhc_type) LIKE \'van%\' THEN \'Van\'\r\n\twhen lower(vhc_type) LIKE \'unkno%\' THEN \'Unknown\'\r\n\twhen lower(vhc_type) LIKE \'other%\' THEN \'Unknown\'\r\n\tELSE vhc_type END AS vhc_type_, vhc_type_am\r\n\tFROM "MVC_summarize".mvc_sum_all \r\n\tWHERE vhc_type IS NOT NULL) vhc_t \r\n GROUP BY vhc_type_)\r\nSELECT vhc_type AS "Vehicle Types involved in Crashes", SUM(vhc_type_am) AS amount\r\nFROM tbl GROUP BY vhc_type ORDER BY amount DESC',
   'template-tags': {}},
  'database': 2},
 'parameter_mappings': [],
 'display': 'pie',
 'collection_preview': True,
 'visualization_settings': {'pie.slice_threshold': 1},
}

"Contributing Factor"
CF = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Contributing Factor',
   'field_ref': ['field', 'Contributing Factor', {'base-type': 'type/Text'}],
   'name': 'Contributing Factor',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 61,
     'nil%': 0.01639344262295082},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 20.0327868852459}}}},
  {'display_name': 'amount',
   'field_ref': ['field', 'amount', {'base-type': 'type/Decimal'}],
   'name': 'amount',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 60,
     'nil%': 0.01639344262295082},
    'type': {'type/Number': {'min': 16,
      'q1': 428.5,
      'q3': 23072,
      'max': 483315,
      'sd': 67172.88479013968,
      'avg': 26099.766666666666}}}}],
 'can_write': True,
 'query_type': 'native',
 'name': 'Contributing Factor',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT contr_f AS "Contributing Factor", SUM(contr_f_am) AS amount\r\nFROM "MVC_summarize".mvc_sum_all GROUP BY contr_f ORDER BY amount DESC',
   'template-tags': {}},
  'database': 2},
 'display': 'pie',
 'collection_preview': True,
 'visualization_settings': {'pie.slice_threshold': 3.5}
}

"Gender of Drivers involved in Crashes"
GD_IC = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Gender of Drivers involved in Crashes',
   'field_ref': ['field',
    'Gender of Drivers involved in Crashes',
    {'base-type': 'type/Text'}],
   'name': 'Gender of Drivers involved in Crashes',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 3, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 5.666666666666667}}}},
  {'display_name': 'sum',
   'field_ref': ['field', 'sum', {'base-type': 'type/Decimal'}],
   'name': 'sum',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 3, 'nil%': 0},
    'type': {'type/Number': {'min': 5068,
      'q1': 118594.5,
      'q3': 1104924.75,
      'max': 1320175,
      'sd': 667962.2497674052,
      'avg': 594805.6666666666}}}}],
 'can_write': True,
 'query_type': 'native',
 'name': 'Gender of Drivers involved in Crashes',
 'dataset_query': {'type': 'native',
  'native': {'query': 'WITH tbl AS( SELECT CASE WHEN sex = \'M\' THEN \'Male\' WHEN sex = \'F\' THEN \'Female\'\r\nELSE \'Unknown\' end as gender, age, age_am  FROM "MVC_summarize".mvc_sum_all )\r\nSELECT gender AS "Gender of Drivers involved in Crashes", SUM(age_am) FROM tbl GROUP BY gender',
   'template-tags': {}},
  'database': 2},
 'parameter_mappings': [],
 'display': 'pie',
 'visualization_settings': {'pie.percent_visibility': 'off'}
}

"MVC_crashes_per_month"
MVC_crashes_per_month = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Date',
   'field_ref': ['field', 'Date', {'base-type': 'type/Text'}],
   'name': 'Date',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 84, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 7}}}},
  {'display_name': 'Crashes/month',
   'field_ref': ['field', 'Crashes/month', {'base-type': 'type/BigInteger'}],
   'name': 'Crashes/month',
   'base_type': 'type/BigInteger',
   'effective_type': 'type/BigInteger',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 84, 'nil%': 0},
    'type': {'type/Number': {'min': 4130,
      'q1': 9326,
      'q3': 19462.96387141212,
      'max': 21373,
      'sd': 5104.496615485636,
      'avg': 14656.130952380952}}}},
  {'display_name': 'Crashes/month with injuries',
   'field_ref': ['field',
    'Crashes/month with injuries',
    {'base-type': 'type/BigInteger'}],
   'name': 'Crashes/month with injuries',
   'base_type': 'type/BigInteger',
   'effective_type': 'type/BigInteger',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 83, 'nil%': 0},
    'type': {'type/Number': {'min': 1312,
      'q1': 4200.5,
      'q3': 5381,
      'max': 5925,
      'sd': 858.5009430344558,
      'avg': 4673.619047619048}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'MVC_crashes_per_month',
 'embedding_params': None,
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT * FROM "MVC_summarize".mvc_crashes_per_month WHERE "month" between 2016 and 2022',
   'template-tags': {}},
  'database': 2},
 'display': 'area',
 'collection_preview': True,
 'visualization_settings': {'stackable.stack_type': None,
  'graph.y_axis.auto_split': False,
  'graph.dimensions': ['Date'],
  'graph.metrics': ['Crashes/month', 'Crashes/month with injuries']}
}

"Age of Drivers involved in Crashes"
AD_iC = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Age of Drivers involved in Crashes',
   'field_ref': ['field',
    'Age of Drivers involved in Crashes',
    {'base-type': 'type/Text'}],
   'name': 'Age of Drivers involved in Crashes',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 7, 'nil%': 0.1428571428571429},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 3.7142857142857144}}}},
  {'display_name': 'amount',
   'field_ref': ['field', 'amount', {'base-type': 'type/Decimal'}],
   'name': 'amount',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 7, 'nil%': 0},
    'type': {'type/Number': {'min': 7066,
      'q1': 40868.25,
      'q3': 424303.5,
      'max': 511123,
      'sd': 216061.26300790577,
      'avg': 254916.7142857143}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Age of Drivers involved in Crashes',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT "age" AS "Age of Drivers involved in Crashes", SUM(age_am) AS amount\r\nFROM "MVC_summarize".mvc_sum_all GROUP BY "age" ORDER BY amount DESC',
   'template-tags': {}},
  'database': 2},
 'display': 'pie',
 'collection_preview': True,
 'visualization_settings': {'pie.slice_threshold': 3}
}

"MVC_crashes_per_hour"
MVC_crashes_per_hour = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Time Interval',
   'field_ref': ['field', 'Time Interval', {'base-type': 'type/Text'}],
   'name': 'Time Interval',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 24, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 11}}}},
  {'display_name': 'Average of all crashes/h',
   'field_ref': ['field',
    'Average of all crashes/h',
    {'base-type': 'type/Decimal'}],
   'name': 'Average of all crashes/h',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 24, 'nil%': 0},
    'type': {'type/Number': {'min': 174.93023255813952,
      'q1': 378.72868217054264,
      'q3': 868.5697674418604,
      'max': 1111.7674418604652,
      'sd': 307.04754791002216,
      'avg': 639.2096253229975}}}},
  {'display_name': 'Average of crashes/h with injuries',
   'field_ref': ['field',
    'Average of crashes/h with injuries',
    {'base-type': 'type/Decimal'}],
   'name': 'Average of crashes/h with injuries',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 24, 'nil%': 0},
    'type': {'type/Number': {'min': 66.86821705426357,
      'q1': 123.4922480620155,
      'q3': 244.25581395348837,
      'max': 318.05426356589146,
      'sd': 78.9368369725386,
      'avg': 189.90826873385012}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'MVC_crashes_per_hour',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT time_interval AS "Time Interval", AVG(all_amount) AS "Average of all crashes/h", AVG(injured_am) AS "Average of crashes/h with injuries"\r\nFROM "MVC_summarize".mvc_crashes_per_hour GROUP BY time_interval ORDER BY "Time Interval"',
   'template-tags': {}},
  'database': 2},
 'display': 'area',
 'visualization_settings': {'stackable.stack_type': None,
  'graph.y_axis.auto_split': False,
  'graph.dimensions': ['Time Interval'],
  'graph.metrics': ['Average of all crashes/h',
   'Average of crashes/h with injuries']}
}


crd_names = [MVC_NYC, MVC_NYC_DO, VT_iiC, CF, GD_IC, MVC_crashes_per_month, AD_iC, MVC_crashes_per_hour]

params = {'Motor Vehicle Collisions (2012-2023) New York City'                    :{'cardId': 1, 'size_x': 6, 'size_y': 6, 'row': 0, 'col':0},
          'Motor Vehicle Collisions (2012-2023) New York City Dataset Overview'   :{'cardId': 2, 'size_x': 12, 'size_y': 6, 'row': 0, 'col':6},
          'Vehicle Types involved in Crashes'                                     :{'cardId': 3, 'size_x': 9, 'size_y': 5, 'row': 6, 'col':9},
          'Contributing Factor'                                                   :{'cardId': 4, 'size_x': 9, 'size_y': 5, 'row': 6, 'col':0},
          'Gender of Drivers involved in Crashes'                                 :{'cardId': 5, 'size_x': 6, 'size_y': 5, 'row': 11, 'col':0},
          'MVC_crashes_per_month'                                                 :{'cardId': 6, 'size_x': 12, 'size_y': 5, 'row': 11, 'col':6},
          'Age of Drivers involved in Crashes'                                    :{'cardId': 7, 'size_x': 7, 'size_y': 5, 'row': 16, 'col':0},
          'MVC_crashes_per_hour'                                                  :{'cardId': 8, 'size_x': 11, 'size_y': 5, 'row': 16, 'col':7}
          }

