from sqlalchemy.types import Integer, Date, Time,Text


url_C = "https://data.cityofnewyork.us/api/views/h9gi-nx95/rows.csv?accessType=DOWNLOAD"

sel_C = [
    "COLLISION_ID",
    "CRASH DATE",
    "CRASH TIME",
    "BOROUGH",
    "NUMBER OF PERSONS INJURED" ,
    "NUMBER OF PERSONS KILLED" ,
    "VEHICLE TYPE CODE 1",
    "CONTRIBUTING FACTOR VEHICLE 1",
    "VEHICLE TYPE CODE 2",
    "CONTRIBUTING FACTOR VEHICLE 2",
    "VEHICLE TYPE CODE 3",
    "CONTRIBUTING FACTOR VEHICLE 3",
    "VEHICLE TYPE CODE 4",
    "CONTRIBUTING FACTOR VEHICLE 4" 
]

sel_rename_C = {
    "COLLISION_ID" : "collision_id",
    "CRASH DATE" : "crash_date",
    "CRASH TIME" : "crash_time",
    "BOROUGH" : "borough",
    "NUMBER OF PERSONS INJURED" : "injured" ,
    "NUMBER OF PERSONS KILLED" : "killed" ,
    "CONTRIBUTING FACTOR VEHICLE 1" : "contr_f_vhc_1",
    "CONTRIBUTING FACTOR VEHICLE 2" : "contr_f_vhc_2",
    "CONTRIBUTING FACTOR VEHICLE 3" : "contr_f_vhc_3",
    "CONTRIBUTING FACTOR VEHICLE 4" : "contr_f_vhc_4",
    "VEHICLE TYPE CODE 1" : "vhc_1_code",
    "VEHICLE TYPE CODE 2" : "vhc_2_code",
    "VEHICLE TYPE CODE 3" : "vhc_3_code",
    "VEHICLE TYPE CODE 4" : "vhc_4_code"
}

sel_types_C = {

    "collision_id" : Integer(),
    "crash_date" : Date(),
    "crash_time" : Time(),
    "borough" : Text(),
    "injured" : Integer(),
    "killed" : Integer(),
    "vhc_1_code" : Text(),
    "contr_f_vhc_1" : Text(),
    "vhc_2_code" : Text(),
    "contr_f_vhc_2" : Text(),
    "vhc_3_code" : Text(),
    "contr_f_vhc_3" : Text(),
    "vhc_4_code" : Text(),
    "contr_f_vhc_4" : Text() 
}


url_V = "https://data.cityofnewyork.us/api/views/bm4k-52h4/rows.csv?accessType=DOWNLOAD"

sel_V = [
  "UNIQUE_ID" ,
  "COLLISION_ID" ,
  "CRASH_DATE" ,
  "CRASH_TIME" ,
  "VEHICLE_TYPE", 
  "VEHICLE_DAMAGE" ,
  "DRIVER_SEX" ,
  "DRIVER_LICENSE_STATUS" ,
  "VEHICLE_YEAR" ,
  "VEHICLE_OCCUPANTS" ,  
  "STATE_REGISTRATION" , 
  "CONTRIBUTING_FACTOR_1"
]

sel_rename_V = {
  "UNIQUE_ID" : "unique_id",
  "COLLISION_ID" : "collision_id",
  "CRASH_DATE" : "crash_date",
  "CRASH_TIME" : "crash_time",
  "STATE_REGISTRATION" : "state_reg",
  "VEHICLE_TYPE" : "vhc_type",
  "VEHICLE_YEAR" : "vhc_year",
  "VEHICLE_OCCUPANTS" : "vhc_occupants",
  "DRIVER_SEX" : "dr_sex",
  "DRIVER_LICENSE_STATUS" : "dr_lic_status",
  "VEHICLE_DAMAGE" : "vhc_dmg",
  "CONTRIBUTING_FACTOR_1" : "contr_f"
}

sel_types_V = {
  "unique_id" : Integer(),
  "collision_id" : Integer(),
  "crash_date" : Date(),
  "crash_time" : Time(),
  "vhc_type" : Text(),
  "vhc_dmg" : Text(),
  "dr_sex" : Text(),
  "dr_lic_status" : Text(),
  "vhc_year"  : Integer(),
  "vhc_occupants"  : Integer(),
  "state_reg" : Text(),
  "contr_f" : Text()
}


url_P = "https://data.cityofnewyork.us/api/views/f55k-p6yu/rows.csv?accessType=DOWNLOAD"

sel_P = [
  "UNIQUE_ID" ,
  "COLLISION_ID",
  "CRASH_DATE" ,
  "CRASH_TIME" ,
  "EJECTION" ,
  "BODILY_INJURY" ,
  "PERSON_INJURY" ,
  "POSITION_IN_VEHICLE" ,
  "SAFETY_EQUIPMENT" ,
  "PERSON_TYPE" ,
  "PERSON_AGE" ,
  "PERSON_SEX",
  "EMOTIONAL_STATUS" ,
  "CONTRIBUTING_FACTOR_1" 
   
]

sel_rename_P = {
 "UNIQUE_ID" : "unique_id",
  "COLLISION_ID" : "collision_id",
  "CRASH_DATE" : "crash_date",
  "CRASH_TIME" : "crash_time",
  "EJECTION" : "ejection",
  "BODILY_INJURY" : "body_inj",
  "PERSON_INJURY" : "person_inj",
  "POSITION_IN_VEHICLE" : "pos_in_vhc",
  "SAFETY_EQUIPMENT" : "safety_equip",
  "PERSON_TYPE" : "person_type",
  "PERSON_AGE" : "age",
  "PERSON_SEX" : "sex",
  "EMOTIONAL_STATUS" : "emot_status",
  "CONTRIBUTING_FACTOR_1" : "contr_f"
}

sel_types_P = {
  "unique_id" : Integer(),
  "collision_id" : Integer(),
  "crash_date" : Date(),
  "crash_time" : Time(),
  "ejection" : Text(),
  "body_inj" : Text(),
  "person_inj" : Text(),
  "pos_in_vhc" : Text(),
  "safety_equip" : Text(),
  "person_type" : Text(),
  "age" : Integer(),
  "sex" : Text(),
  "emot_status" : Text(),
  "contr_f" : Text()
}





"Motor Vehicle Collisions (2012-2023) New York City" 
MVC_NYC = {'description': None,
 'archived': False,
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Motor Vehicle Collisions (2012-2023) New York City',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT SUM(total_crashes_am) AS "Total Crashes", SUM(total_vhc_am) AS "Total Vehicles involved in Crashes", SUM(total_person_am)  AS "Total Persons involved in Crashes"\r\nFROM "MVC_summarize".mvc_dataset_overview',
   'template-tags': {}},
  'database': 2},
 'display': 'object',
 'collection_preview': True,
 'visualization_settings': {'column_settings': {'["name","sum"]': {'column_title': 'Total Crashes'},
   '["name","sum_2"]': {'column_title': 'Total Vehicles involved in Crashes'},
   '["name","sum_3"]': {'column_title': 'Total Persons involved in Crashes'}}}
}

"Motor Vehicle Collisions (2012-2023) New York City Dataset Overview"
MVC_NYC_DO = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'year',
   'field_ref': ['field', 'year', {'base-type': 'type/Integer'}],
   'name': 'year',
   'base_type': 'type/Integer',
   'effective_type': 'type/Integer',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 12, 'nil%': 0.0},
    'type': {'type/Number': {'min': 2012.0,
      'q1': 2014.5,
      'q3': 2020.5,
      'max': 2023.0,
      'sd': 3.605551275463989,
      'avg': 2017.5}}}},
  {'display_name': 'No Vhc Data %',
   'field_ref': ['field', 'No Vhc Data %', {'base-type': 'type/Decimal'}],
   'name': 'No Vhc Data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 7, 'nil%': 0.0},
    'type': {'type/Number': {'min': 0.0,
      'q1': 0.008284271247461903,
      'q3': 3.995,
      'max': 100.0,
      'sd': 38.664675082592176,
      'avg': 17.340833333333332}}}},
  {'display_name': 'No Person Data %',
   'field_ref': ['field', 'No Person Data %', {'base-type': 'type/Decimal'}],
   'name': 'No Person Data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 11, 'nil%': 0.0},
    'type': {'type/Number': {'min': 0.09,
      'q1': 0.26556349186104045,
      'q3': 80.08500000000001,
      'max': 82.47,
      'sd': 39.089427414661124,
      'avg': 28.460833333333337}}}},
  {'display_name': 'No Vhc Type Data %',
   'field_ref': ['field', 'No Vhc Type Data %', {'base-type': 'type/Decimal'}],
   'name': 'No Vhc Type Data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 11, 'nil%': 0.0},
    'type': {'type/Number': {'min': 0.02,
      'q1': 0.24,
      'q3': 13.629999999999999,
      'max': 100.0,
      'sd': 37.10241708821514,
      'avg': 21.270833333333332}}}},
  {'display_name': 'No Age Data %',
   'field_ref': ['field', 'No Age Data %', {'base-type': 'type/Decimal'}],
   'name': 'No Age Data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 12, 'nil%': 0.0},
    'type': {'type/Number': {'min': 1.86,
      'q1': 13.66,
      'q3': 74.515,
      'max': 77.52,
      'sd': 30.936163745246876,
      'avg': 34.675000000000004}}}},
  {'display_name': 'No Sex Data %',
   'field_ref': ['field', 'No Sex Data %', {'base-type': 'type/Decimal'}],
   'name': 'No Sex Data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 11, 'nil%': 0.0},
    'type': {'type/Number': {'min': 14.45,
      'q1': 15.594999999999999,
      'q3': 99.82,
      'max': 99.93,
      'sd': 41.12403679446763,
      'avg': 44.262499999999996}}}},
  {'display_name': 'No Borough Data %',
   'field_ref': ['field', 'No Borough Data %', {'base-type': 'type/Decimal'}],
   'name': 'No Borough Data %',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 12, 'nil%': 0.0},
    'type': {'type/Number': {'min': 22.84,
      'q1': 24.515,
      'q3': 34.975,
      'max': 38.12,
      'sd': 5.595830360566912,
      'avg': 31.19583333333333}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Motor Vehicle Collisions (2012-2023) New York City Dataset Overview',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT "year", "no_vhc_data_%" AS "No Vhc Data %", "no_person_data_%" AS "No Person Data %",  "no_vhc_type_data_%" AS "No Vhc Type Data %", \r\n"no_age_data_%" AS "No Age Data %", "no_sex_data_%" AS "No Sex Data %", "no_borough_data_%" AS "No Borough Data %"\r\nFROM "MVC_summarize".mvc_dataset_overview',
   'template-tags': {}},
  'database': 2},
 'parameter_mappings': [],
 'display': 'bar',
 'collection_preview': True,
 'visualization_settings': {'graph.dimensions': ['year'],
  'graph.series_order_dimension': None,
  'graph.series_order': None,
  'graph.y_axis.auto_split': False,
  'graph.metrics': ['No Vhc Data %',
   'No Person Data %',
   'No Vhc Type Data %',
   'No Age Data %',
   'No Sex Data %',
   'No Borough Data %']}
}

"Vehicle Types involved in Crashes"
VT_iiC = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Vehicle Types involved in Crashes',
   'field_ref': ['field',
    'Vehicle Types involved in Crashes',
    {'base-type': 'type/Text'}],
   'name': 'Vehicle Types involved in Crashes',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 372, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0.005376344086021505,
      'average-length': 6.599462365591398}}}},
  {'display_name': 'amount',
   'field_ref': ['field', 'amount', {'base-type': 'type/Decimal'}],
   'name': 'amount',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 123, 'nil%': 0},
    'type': {'type/Number': {'min': 3,
      'q1': 6.4829120355062635,
      'q3': 40.877249736984304,
      'max': 1030335,
      'sd': 80954.95294135342,
      'avg': 9472.002688172042}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Vehicle Types involved in Crashes',
 'dataset_query': {'type': 'native',
  'native': {'query': 'with tbl AS(\r\nSELECT vhc_type_ AS vhc_type, SUM(vhc_type_am) AS vhc_type_am FROM (\r\n\tSELECT CASE\r\n\tWHEN lower(vhc_type) LIKE \'passenger%\' THEN \'Passenger Vehicle\'\r\n\twhen lower(vhc_type) LIKE \'%sport utility%\' THEN \'Sport Utility / Station Wagon\'\r\n\twhen lower(vhc_type) LIKE \'taxi%\' THEN \'Taxi\'\r\n\twhen lower(vhc_type) LIKE \'pick%\' THEN \'Pick-up Truck\'\r\n\twhen lower(vhc_type) LIKE \'bus%\' THEN \'Bus\'\r\n\twhen lower(vhc_type) LIKE \'van%\' THEN \'Van\'\r\n\twhen lower(vhc_type) LIKE \'unkno%\' THEN \'Unknown\'\r\n\twhen lower(vhc_type) LIKE \'other%\' THEN \'Unknown\'\r\n\tELSE vhc_type END AS vhc_type_, vhc_type_am\r\n\tFROM "MVC_summarize".mvc_sum_all \r\n\tWHERE vhc_type IS NOT NULL) vhc_t \r\n GROUP BY vhc_type_)\r\nSELECT vhc_type AS "Vehicle Types involved in Crashes", SUM(vhc_type_am) AS amount\r\nFROM tbl GROUP BY vhc_type ORDER BY amount DESC',
   'template-tags': {}},
  'database': 2},
 'parameter_mappings': [],
 'display': 'pie',
 'collection_preview': True,
 'visualization_settings': {'pie.slice_threshold': 1},
}

"Contributing Factor"
CF = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Contributing Factor',
   'field_ref': ['field', 'Contributing Factor', {'base-type': 'type/Text'}],
   'name': 'Contributing Factor',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 61,
     'nil%': 0.01639344262295082},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 20.0327868852459}}}},
  {'display_name': 'amount',
   'field_ref': ['field', 'amount', {'base-type': 'type/Decimal'}],
   'name': 'amount',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 60,
     'nil%': 0.01639344262295082},
    'type': {'type/Number': {'min': 16,
      'q1': 428.5,
      'q3': 23072,
      'max': 483315,
      'sd': 67172.88479013968,
      'avg': 26099.766666666666}}}}],
 'can_write': True,
 'query_type': 'native',
 'name': 'Contributing Factor',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT contr_f AS "Contributing Factor", SUM(contr_f_am) AS amount\r\nFROM "MVC_summarize".mvc_sum_all GROUP BY contr_f ORDER BY amount DESC',
   'template-tags': {}},
  'database': 2},
 'display': 'pie',
 'collection_preview': True,
 'visualization_settings': {'pie.slice_threshold': 3.5}
}

"Gender of Drivers involved in Crashes"
GD_IC = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Gender of Drivers involved in Crashes',
   'field_ref': ['field',
    'Gender of Drivers involved in Crashes',
    {'base-type': 'type/Text'}],
   'name': 'Gender of Drivers involved in Crashes',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 3, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 5.666666666666667}}}},
  {'display_name': 'sum',
   'field_ref': ['field', 'sum', {'base-type': 'type/Decimal'}],
   'name': 'sum',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 3, 'nil%': 0},
    'type': {'type/Number': {'min': 5068,
      'q1': 118594.5,
      'q3': 1104924.75,
      'max': 1320175,
      'sd': 667962.2497674052,
      'avg': 594805.6666666666}}}}],
 'can_write': True,
 'query_type': 'native',
 'name': 'Gender of Drivers involved in Crashes',
 'dataset_query': {'type': 'native',
  'native': {'query': 'WITH tbl AS( SELECT CASE WHEN sex = \'M\' THEN \'Male\' WHEN sex = \'F\' THEN \'Female\'\r\nELSE \'Unknown\' end as gender, age, age_am  FROM "MVC_summarize".mvc_sum_all )\r\nSELECT gender AS "Gender of Drivers involved in Crashes", SUM(age_am) FROM tbl GROUP BY gender',
   'template-tags': {}},
  'database': 2},
 'parameter_mappings': [],
 'display': 'pie',
 'visualization_settings': {'pie.percent_visibility': 'off'}
}

"MVC_crashes_per_month"
MVC_crashes_per_month = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Date',
   'field_ref': ['field', 'Date', {'base-type': 'type/Text'}],
   'name': 'Date',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 84, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 7}}}},
  {'display_name': 'Crashes/month',
   'field_ref': ['field', 'Crashes/month', {'base-type': 'type/BigInteger'}],
   'name': 'Crashes/month',
   'base_type': 'type/BigInteger',
   'effective_type': 'type/BigInteger',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 84, 'nil%': 0},
    'type': {'type/Number': {'min': 4130,
      'q1': 9326,
      'q3': 19462.96387141212,
      'max': 21373,
      'sd': 5104.496615485636,
      'avg': 14656.130952380952}}}},
  {'display_name': 'Crashes/month with injuries',
   'field_ref': ['field',
    'Crashes/month with injuries',
    {'base-type': 'type/BigInteger'}],
   'name': 'Crashes/month with injuries',
   'base_type': 'type/BigInteger',
   'effective_type': 'type/BigInteger',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 83, 'nil%': 0},
    'type': {'type/Number': {'min': 1312,
      'q1': 4200.5,
      'q3': 5381,
      'max': 5925,
      'sd': 858.5009430344558,
      'avg': 4673.619047619048}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'MVC_crashes_per_month',
 'embedding_params': None,
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT concat("year",\'-\',TO_CHAR("month",\'fm09\')) AS "Date", SUM(all_amount)AS "Crashes/month",\r\nSUM(injured_am) AS "Crashes/month with injuries"\r\nFROM "MVC_summarize".mvc_crashes_per_hour \r\nWHERE "year" between 2016 and 2022\r\nGROUP BY concat("year",\'-\',TO_CHAR("month",\'fm09\')) \r\nORDER BY "Date"',
   'template-tags': {}},
  'database': 2},
 'display': 'area',
 'collection_preview': True,
 'visualization_settings': {'stackable.stack_type': None,
  'graph.y_axis.auto_split': False,
  'graph.dimensions': ['Date'],
  'graph.metrics': ['Crashes/month', 'Crashes/month with injuries']}
}

"Age of Drivers involved in Crashes"
AD_iC = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Age of Drivers involved in Crashes',
   'field_ref': ['field',
    'Age of Drivers involved in Crashes',
    {'base-type': 'type/Text'}],
   'name': 'Age of Drivers involved in Crashes',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 7, 'nil%': 0.1428571428571429},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 3.7142857142857144}}}},
  {'display_name': 'amount',
   'field_ref': ['field', 'amount', {'base-type': 'type/Decimal'}],
   'name': 'amount',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 7, 'nil%': 0},
    'type': {'type/Number': {'min': 7066,
      'q1': 40868.25,
      'q3': 424303.5,
      'max': 511123,
      'sd': 216061.26300790577,
      'avg': 254916.7142857143}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'Age of Drivers involved in Crashes',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT "age" AS "Age of Drivers involved in Crashes", SUM(age_am) AS amount\r\nFROM "MVC_summarize".mvc_sum_all GROUP BY "age" ORDER BY amount DESC',
   'template-tags': {}},
  'database': 2},
 'display': 'pie',
 'collection_preview': True,
 'visualization_settings': {'pie.slice_threshold': 3}
}

"MVC_crashes_per_hour"
MVC_crashes_per_hour = {'description': None,
 'archived': False,
 'collection_position': None,
 'table_id': None,
 'result_metadata': [{'display_name': 'Time Interval',
   'field_ref': ['field', 'Time Interval', {'base-type': 'type/Text'}],
   'name': 'Time Interval',
   'base_type': 'type/Text',
   'effective_type': 'type/Text',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 24, 'nil%': 0},
    'type': {'type/Text': {'percent-json': 0,
      'percent-url': 0,
      'percent-email': 0,
      'percent-state': 0,
      'average-length': 11}}}},
  {'display_name': 'Average of all crashes/h',
   'field_ref': ['field',
    'Average of all crashes/h',
    {'base-type': 'type/Decimal'}],
   'name': 'Average of all crashes/h',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 24, 'nil%': 0},
    'type': {'type/Number': {'min': 174.93023255813952,
      'q1': 378.72868217054264,
      'q3': 868.5697674418604,
      'max': 1111.7674418604652,
      'sd': 307.04754791002216,
      'avg': 639.2096253229975}}}},
  {'display_name': 'Average of crashes/h with injuries',
   'field_ref': ['field',
    'Average of crashes/h with injuries',
    {'base-type': 'type/Decimal'}],
   'name': 'Average of crashes/h with injuries',
   'base_type': 'type/Decimal',
   'effective_type': 'type/Decimal',
   'semantic_type': None,
   'fingerprint': {'global': {'distinct-count': 24, 'nil%': 0},
    'type': {'type/Number': {'min': 66.86821705426357,
      'q1': 123.4922480620155,
      'q3': 244.25581395348837,
      'max': 318.05426356589146,
      'sd': 78.9368369725386,
      'avg': 189.90826873385012}}}}],
 'can_write': True,
 'enable_embedding': False,
 'query_type': 'native',
 'name': 'MVC_crashes_per_hour',
 'dataset_query': {'type': 'native',
  'native': {'query': 'SELECT time_interval AS "Time Interval", AVG(all_amount) AS "Average of all crashes/h", AVG(injured_am) AS "Average of crashes/h with injuries"\r\nFROM "MVC_summarize".mvc_crashes_per_hour GROUP BY time_interval ORDER BY "Time Interval"',
   'template-tags': {}},
  'database': 2},
 'display': 'area',
 'visualization_settings': {'stackable.stack_type': None,
  'graph.y_axis.auto_split': False,
  'graph.dimensions': ['Time Interval'],
  'graph.metrics': ['Average of all crashes/h',
   'Average of crashes/h with injuries']}
}


crd_names = [MVC_NYC, MVC_NYC_DO, VT_iiC, CF, GD_IC, MVC_crashes_per_month, AD_iC, MVC_crashes_per_hour]